In [3]:
import pandas as pd
import numpy as np

df = pd.read_csv("./data/auto-mpg.csv", header=None)

df.columns = [
    "mpg",
    "cylinders",
    "displacement",
    "horsepower",
    "weight",
    "acceleration",
    "model_year",
    "origin",
    "name"
]

df['horsepower'] = df['horsepower'].replace("?", np.nan)
df = df.dropna(subset=['horsepower'], axis=0)
df["horsepower"] = df["horsepower"].astype('float')
df.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
0,18.0,8,307.0,130.0,3504.0,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165.0,3693.0,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150.0,3436.0,11.0,70,1,plymouth satellite
3,16.0,8,304.0,150.0,3433.0,12.0,70,1,amc rebel sst
4,17.0,8,302.0,140.0,3449.0,10.5,70,1,ford torino

In [4]:
df['horsepower'].describe()

count    392.000000
mean     104.469388
std       38.491160
min       46.000000
25%       75.000000
50%       93.500000
75%      126.000000
max      230.000000
Name: horsepower, dtype: float64

In [5]:
count, bin_dividers = np.histogram(df['horsepower'], bins=3)

print(count)
print(bin_dividers)

[257 103  32]
[ 46.         107.33333333 168.66666667 230.        ]

In [7]:
bin_names = ["저출력", "보통출력", "고출력"]

df["hp_bin"] = pd.cut(
    x=df['horsepower'], 
    bins=bin_dividers,
    labels=bin_names,
    include_lowest=True
)
df[['horsepower', 'hp_bin']].head(15)

    horsepower hp_bin
0        130.0   보통출력
1        165.0   보통출력
2        150.0   보통출력
3        150.0   보통출력
4        140.0   보통출력
5        198.0    고출력
6        220.0    고출력
7        215.0    고출력
8        225.0    고출력
9        190.0    고출력
10       170.0    고출력
11       160.0   보통출력
12       150.0   보통출력
13       225.0    고출력
14        95.0    저출력

In [8]:
# 더미변수
df['hp_bin']

0      보통출력
1      보통출력
2      보통출력
3      보통출력
4      보통출력
       ...
393     저출력
394     저출력
395     저출력
396     저출력
397     저출력
Name: hp_bin, Length: 392, dtype: category
Categories (3, str): ['저출력' < '보통출력' < '고출력']

In [9]:
df['hp_bin'].value_counts()

hp_bin
저출력     257
보통출력    103
고출력      32
Name: count, dtype: int64

In [ ]:
pd.get_dummies(df['hp_bin']) # 시리즈 형태가 데이터프레임 형태로

       저출력   보통출력    고출력
0    False   True  False
1    False   True  False
2    False   True  False
3    False   True  False
4    False   True  False
..     ...    ...    ...
393   True  False  False
394   True  False  False
395   True  False  False
396   True  False  False
397   True  False  False

[392 rows x 3 columns]

In [12]:
pd.get_dummies(df['hp_bin'], dtype=float)

     저출력  보통출력  고출력
0    0.0   1.0  0.0
1    0.0   1.0  0.0
2    0.0   1.0  0.0
3    0.0   1.0  0.0
4    0.0   1.0  0.0
..   ...   ...  ...
393  1.0   0.0  0.0
394  1.0   0.0  0.0
395  1.0   0.0  0.0
396  1.0   0.0  0.0
397  1.0   0.0  0.0

[392 rows x 3 columns]

In [18]:
pd.get_dummies(df['hp_bin'], dtype=float, drop_first=True) # drop_first = > 변환할 때 첫번째 열을 제거

     보통출력  고출력
0     1.0  0.0
1     1.0  0.0
2     1.0  0.0
3     1.0  0.0
4     1.0  0.0
..    ...  ...
393   0.0  0.0
394   0.0  0.0
395   0.0  0.0
396   0.0  0.0
397   0.0  0.0

[392 rows x 2 columns]

In [20]:
from sklearn import preprocessing # import LabelEncoder, OneHotEncoder   # pip install scikit-learn

label_encoder = preprocessing.LabelEncoder()
onehot_encoder = preprocessing.OneHotEncoder()

onehot_labeled = label_encoder.fit_transform(df['hp_bin'].head(15))

print(onehot_labeled)

print(type(onehot_labeled))

print(onehot_labeled.ndim)

[1 1 1 1 1 0 0 0 0 0 0 1 1 0 2]
<class 'numpy.ndarray'>
1

In [22]:
onehot_reshaped = onehot_labeled.reshape(len(onehot_labeled), 1)

onehot_fitted = onehot_encoder.fit_transform(onehot_reshaped)

print(onehot_fitted)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 15 stored elements and shape (15, 3)>
  Coords	Values
  (0, 1)	1.0
  (1, 1)	1.0
  (2, 1)	1.0
  (3, 1)	1.0
  (4, 1)	1.0
  (5, 0)	1.0
  (6, 0)	1.0
  (7, 0)	1.0
  (8, 0)	1.0
  (9, 0)	1.0
  (10, 0)	1.0
  (11, 1)	1.0
  (12, 1)	1.0
  (13, 0)	1.0
  (14, 2)	1.0