In [43]:
import pandas as pd

# 1번문제 
info = {
    "이름" : ["김철수", "이영희", "박민수", "최지우"],
    "나이" : [20, 21, 22, 20],
    "성별" : ["남", "여", "남", "여"],
    "수학" : [90, 85, 70, 100],
    "영어" : [85, 95, 75, 90]
}
# 1
df = pd.DataFrame(info)
# 2
print(df.iloc[:2])
# 3
df.dtypes

    이름  나이 성별  수학  영어
0  김철수  20  남  90  85
1  이영희  21  여  85  95

이름      str
나이    int64
성별      str
수학    int64
영어    int64
dtype: object

In [ ]:
# 4
df = df.set_index("이름")
df

     나이 성별   수학  영어
이름
김철수  20  남   90  85
이영희  21  여   85  95
박민수  22  남   70  75
최지우  20  여  100  90

In [ ]:
# 5
df.loc["이영희", ["수학", "영어"]] # loc에서 슬랑싱은 뒷 데이터까지 나옴

수학    85
영어    95
Name: 이영희, dtype: int64

In [46]:
# 6

df.iloc[0:2,2:]

  성별  수학  영어
0  남  90  85
1  여  85  95

In [ ]:
# 2번문제

info = {
    "이름" : ["김철수", "이영희", "박민수", "최지우"],
    "나이" : [20, 21, 22, 20],
    "성별" : ["남", "여", "남", "여"],
    "수학" : [90, 85, 70, 100],
    "영어" : [85, 95, 75, 90]
}
# 1
sr = pd.Series(info)
sr

이름    [김철수, 이영희, 박민수, 최지우]
나이        [20, 21, 22, 20]
성별            [남, 여, 남, 여]
수학       [90, 85, 70, 100]
영어        [85, 95, 75, 90]
dtype: object

In [21]:
# 2
print(sr.index)
print(sr.values)

Index(['이름', '나이', '성별', '수학', '영어'], dtype='str')
[list(['김철수', '이영희', '박민수', '최지우']) list([20, 21, 22, 20])
 list(['남', '여', '남', '여']) list([90, 85, 70, 100]) list([85, 95, 75, 90])]

In [48]:
# 3
list_data = ["2010-01-02", 3.14, "ABC", 100, True]

sr1 = pd.Series(list_data)
# 4
sr1.dtype

dtype('O')

In [ ]:
#5
tup_data = ("영인", "2010-05-01", "여", True)
index_labels = ["이름", "생년월일", "성별", "학생여부"]

sr2 = pd.Series(tup_data, index= index_labels)
sr2

이름              영인
생년월일    2010-05-01
성별               여
학생여부          True
dtype: object

In [ ]:
print(f"원소 개수: {sr2.size}, 형상(shape): {sr2.shape}, 차원: {sr2.ndim}")

len(sr2)
sr.shape # 형상
sr.ndim # 차원

원소 개수: 4, 형상(shape): (4,), 차원: 1

In [ ]:
# 7
print(sr2.iloc[0])

영인

In [33]:
# 8 
print(sr2.loc['이름'])

영인

In [ ]:
# 9
print(sr2.iloc[[1, 2]])

생년월일    2010-05-01
성별               여
dtype: object

In [49]:
# 10
print(sr2.loc[['생년월일', '성별']])

print(sr2.iloc[1:3])

생년월일    2010-05-01
성별               여
dtype: object
생년월일    2010-05-01
성별               여
dtype: object

In [ ]:
# 11
empty_sr = pd.Series()
empty_sr

In [38]:
sr4 = pd.Series(5, index=["a", "b", "c"])
sr4

a    5
b    5
c    5
dtype: int64